# Generated by Django 6.0.4 on 2026-05-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='partner_message',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
